import { IPost } from '@/shared/lib/api/interfaces'

export const postListApiMock: IPost[] = [
  {
    id: '0',
    authorNickname: '@User4jr5',
    authorUUID: 'hhhhhhhhhhhhhhh',
    likesCount: 3,
    dislikesCount: 2,
    content: 'This is the best known and second most common type of lightning. Of all the different types of lightning, it poses the greatest threat to life and property since it strikes the ground. Cloud-to-ground lightning is a lightning discharge between a cumulonimbus cloud and the ground.',
    createdAt: '23s',
    authorAddress: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
    userReaction: 'LIKE',
  },
  {
    id: '1',
    authorNickname: '@User4jr5',
    authorUUID: 'hhhhhhhhhhhhhhh',
    likesCount: 4,
    dislikesCount: 3,
    content: 'This is the best known and second most common type of lightning. Of all the different types of lightning, it poses the greatest threat to life and property since it strikes the ground. Cloud-to-ground lightning is a lightning discharge between a cumulonimbus cloud and the ground.',
    createdAt: '23s',
    authorAddress: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
    userReaction: 'DISLIKE',
  },
  {
    id: '2',
    authorNickname: '@User4jr5',
    authorUUID: 'hhhhhhhhhhhhhhh',
    likesCount: 2,
    dislikesCount: 1,
    content: 'This is the best known and second most common type of lightning. Of all the different types of lightning, it poses the greatest threat to life and property since it strikes the ground. Cloud-to-ground lightning is a lightning discharge between a cumulonimbus cloud and the ground.',
    createdAt: '23s',
    authorAddress: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
    userReaction: 'DISLIKE',
  },
  {
    id: '3',
    authorNickname: '@User4jr5',
    authorUUID: 'hhhhhhhhhhhhhhh',
    likesCount: 1,
    dislikesCount: 2,
    content: 'This is the best known and second most common type of lightning. Of all the different types of lightning, it poses the greatest threat to life and property since it strikes the ground. Cloud-to-ground lightning is a lightning discharge between a cumulonimbus cloud and the ground.',
    createdAt: '23s',
    authorAddress: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
    userReaction: null,
  },
  {
    id: '4',
    authorNickname: '@User4jr5',
    authorUUID: 'hhhhhhhhhhhhhhh',
    likesCount: 1,
    dislikesCount: 2,
    content: 'This is the best known and second most common type of lightning. Of all the different types of lightning, it poses the greatest threat to life and property since it strikes the ground. Cloud-to-ground lightning is a lightning discharge between a cumulonimbus cloud and the ground.',
    createdAt: '23s',
    authorAddress: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
    userReaction: null,
  },
]
